### PR TITLE
Caster3 plugin state

### PR DESCRIPTION
**Pull request by Timoses**
Plugins can use a persistent state store which by default is localized under the configuration directory.

BringMeProgram is implemented (from https://github.com/dictation-toolbox/Caster/blob/master/castervoice/rules/ccr/recording_rules/bringme.py) as a reference for further implementations.

### CODE REVIEW

**Comment by Timoses** [comment]
@LexiconCode : Thought you might be interested in the BringMe implementation approach and have some insight.

**Comment by Timoses** [comment]
> There's still a bug with it. I'm resolving...

Got it ...

**Comment by LexiconCode** [comment]
Taking some time. Note think rule/plug-in.  Still a little bit over my head but I see you've actually done 2 things here in this PR. You've created your own self modifying plug-in and you built a "bring me" plug-in using that functionality. However I'm not seeing abstraction between the implementation between the functionality of self modifying plug-in and the bring me plug-in. 

Anyone that wants to create a plug-in that modifies itself should be able to reuse your work. This is in caster now this is implemented by inheritance through base class and leverages dependency injection to minimize imports. Perhaps I'm missing something.

By doing inheritance you can implement some of the core functionality or let the user override to implement your custom functionality. Perhaps the clearest example is in [hooks](https://github.com/dictation-toolbox/Caster/tree/master/castervoice/lib/merge/ccrmerging2/hooks) and [events](https://github.com/dictation-toolbox/Caster/tree/master/castervoice/lib/merge/ccrmerging2/hooks/events). 

This made implementing [show_window_on_error_hook.py](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/merge/ccrmerging2/hooks/standard_hooks/show_window_on_error_hook.py) a breeze once I understood the workings.

**Comment by Timoses** [comment]
The only abstraction is that of the plugin's state. A plugin implementation does not need to worry about where or how the state is stored or loaded.

The state
* can contain any data structure
* is loaded automatically for the plugin after the base plugin `__init__` method is called
* is only stored when the `Plugin.persist_state()` is called
    * this could be extended to allow the plugin to configure various storing behaviours (like on every change, every X seconds, ...)

I think the idea here is to allow freedom. It is not apparent to me what inheritance or abstraction would be required (e.g. I'm not certain what `_deserialize` is supposed to mean. I guess it "deserializes" the configuration into the mapping rule. But then why restrict it to a mystic `_deserialize` method which is only called once from the base class on initialization?).

A plugin's state could be used for more than just self-modifying behavior. For example, a plugin could be used to control an LED light which had to be set up using some form of manual key exchange. The plugin's state could be used to store that key and load it the next time Caster starts. Of course in that example encryption might also be something to think about.


Imo the question of eventing is another beast that [we should tackle separately](https://github.com/Timoses/Caster/issues/13).

**Comment by LexiconCode** [comment]
yes I can understand state but when designing rules users need guidance how to create rule types [selfmodrule](https://github.com/dictation-toolbox/Caster/blob/f495599e417a8e62f5bafc4aa0b63375dd64b85a/castervoice/lib/merge/selfmod/selfmodrule.py)

I think we need to define what is a rule versus what is a plug-in is getting a bit confusing.

**Comment by Timoses** [comment]
Imo, basic abstractions (like a plugin state) is as far as Caster Core should go. If there is a need for a framework which users can use (which e.g. could contain a SelfModRule base class) then they can use that. If they want another framework they can use that. It's all about not limiting a plugin to specific implementations but giving plugins the freedom to choose how they'd like to implement things. If a framework is the way to go, great. If it doesn't fit the nature of the plugin: Great, you can choose your own way. -> Caster Core shouldn't get in the way.

All that Caster Core should provide is a performant base layer upon which plugins can build onto. And if later there are plugins which require more performance from a state (like larger data structures) then Caster can provide a more performant database backend (or the like).

Regarding Caster as a whole it would be:
* Caster Core
* plus Caster's interpretation of Voice Coding/Commands including a grammar philosophy.

I'm currently focusing on _Caster Core_ trying to support as many philosophies as possible.

As I currently see it a **plugin** implements grammars. Caster Core just fetches these grammars from the plugin and loads it into the SR engine / Dragonfly.

We can also have another voice chat about it if you like ; ).

**Comment by LexiconCode** [comment]
That does clarify your approach. I agree plug-ins should have freedom to define themselves. However we need a way to balance the freedom with a level of abstraction that is accessible to users. Many people come to the caster project simply because dragonfly natively is too complex to easily reimplement many of the features for caster.

Perhaps 'core plug-ins' which are meant to extend base functionality that other plug-ins can rely on that are registered with Caster Core? Provide custom actions and rule types like self modify could register to the framework. This gives the freedom to those that want to bypass higher levels of abstraction (core plug-ins) the record to go straight to Caster Core for all implementation.

**Comment by Timoses** [comment]
Yep, that's probably something of the sorts on the second point from

> Regarding Caster as a whole it would be:
>  *  Caster Core
>  *  plus Caster's interpretation of Voice Coding/Commands including a grammar philosophy.

You could call it a *Caster Framework*.

I'll merge this PR. 

Next step is to get some documentation going so others may get a better understanding of the goals, how to use plugins, etc... I'll try to get a base going and create a PR.

**Pull request merged**
